# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd55d2a3a8c15b0aab7394798d1ccd810d3084e4fd6a489fa3b99695837fb8041bccd5b0a4aa416af3682ab61fd2e33bddad72c423c32035ac008b7da6c3dcf6

test:
  secret_key_base: 05d47a988b691a3dc2692e6b1c37e32b960a767b339a0a37a42b927539fde0f8e90b3a2e69eb6cc4dca47c834d2678fbf682a9c6cac20617c25bb6fab23a5843

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
